"""Updated models for new TimescaleDB schema"""

from sqlalchemy import Column, Integer, String, Float, ForeignKey, Text, Boolean, TIMESTAMP, BigInteger, SmallInteger
from sqlalchemy.dialects.postgresql import JSONB, CHAR
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from geoalchemy2 import Geography
from app.models.base import Base


class Provider(Base):
    """Data providers (AirVisual, etc.)"""
    __tablename__ = "providers"
    
    id = Column(SmallInteger, primary_key=True)
    code = Column(String, unique=True, nullable=False)
    display_name = Column(String, nullable=False)
    api_url = Column(String)
    provider_metadata = Column("metadata", JSONB)
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    
    stations = relationship("Station", back_populates="provider")


class Country(Base):
    """Countries with optional boundaries"""
    __tablename__ = "countries"
    
    id = Column(BigInteger, primary_key=True)
    name = Column(String, unique=True, nullable=False)
    iso2 = Column(CHAR(2))
    iso3 = Column(CHAR(3))
    geom = Column(Geography('MULTIPOLYGON', srid=4326))
    centroid = Column(Geography('POINT', srid=4326))
    population = Column(BigInteger)
    active = Column(Boolean, nullable=False, default=True)
    last_seen_at = Column(TIMESTAMP(timezone=True))
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    
    states = relationship("State", back_populates="country")
    cities = relationship("City", back_populates="country")
    stations = relationship("Station", back_populates="country")


class State(Base):
    """States/provinces/regions"""
    __tablename__ = "states"
    
    id = Column(BigInteger, primary_key=True)
    country_id = Column(BigInteger, ForeignKey("countries.id", ondelete="CASCADE"), nullable=False)
    name = Column(String, nullable=False)
    code = Column(String)
    geom = Column(Geography('MULTIPOLYGON', srid=4326))
    centroid = Column(Geography('POINT', srid=4326))
    population = Column(BigInteger)
    active = Column(Boolean, nullable=False, default=True)
    last_seen_at = Column(TIMESTAMP(timezone=True))
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    
    country = relationship("Country", back_populates="states")
    cities = relationship("City", back_populates="state")
    stations = relationship("Station", back_populates="state")


class City(Base):
    """Cities with normalized scope keys"""
    __tablename__ = "cities"
    
    id = Column(BigInteger, primary_key=True)
    country_id = Column(BigInteger, ForeignKey("countries.id", ondelete="CASCADE"), nullable=False)
    state_id = Column(BigInteger, ForeignKey("states.id", ondelete="CASCADE"))
    name = Column(String, nullable=False)
    geom = Column(Geography('MULTIPOLYGON', srid=4326))
    centroid = Column(Geography('POINT', srid=4326))
    population = Column(BigInteger)
    timezone = Column(String)
    active = Column(Boolean, nullable=False, default=True)
    last_seen_at = Column(TIMESTAMP(timezone=True))
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    scope_key = Column(String)  # Generated by trigger
    
    country = relationship("Country", back_populates="cities")
    state = relationship("State", back_populates="cities")
    stations = relationship("Station", back_populates="city")


class Station(Base):
    """Monitoring stations with 16-char hex IDs"""
    __tablename__ = "stations"
    
    station_id = Column(CHAR(16), primary_key=True)
    country_id = Column(BigInteger, ForeignKey("countries.id", ondelete="RESTRICT"), nullable=False)
    state_id = Column(BigInteger, ForeignKey("states.id", ondelete="SET NULL"))
    city_id = Column(BigInteger, ForeignKey("cities.id", ondelete="SET NULL"))
    name = Column(String, nullable=False)
    lat = Column(Float, nullable=False)
    lon = Column(Float, nullable=False)
    geom = Column(Geography('POINT', srid=4326))  # Generated column
    provider_id = Column(SmallInteger, ForeignKey("providers.id", ondelete="RESTRICT"), nullable=False)
    source_station_id = Column(String)
    elevation_m = Column(Float)
    metadata_json = Column(JSONB)
    timezone = Column(String)
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    
    country = relationship("Country", back_populates="stations")
    state = relationship("State", back_populates="stations")
    city = relationship("City", back_populates="stations")
    provider = relationship("Provider", back_populates="stations")


class StationVersion(Base):
    """Station change history"""
    __tablename__ = "station_versions"
    
    id = Column(BigInteger, primary_key=True)
    station_id = Column(CHAR(16), ForeignKey("stations.station_id", ondelete="CASCADE"))
    valid_from = Column(TIMESTAMP(timezone=True), nullable=False)
    valid_to = Column(TIMESTAMP(timezone=True))
    name = Column(String)
    lat = Column(Float)
    lon = Column(Float)
    metadata_json = Column(JSONB)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())